
name: CI

on:
  push:
    branches:
    - 'v*'

jobs:
  build_on_mac:
    runs-on: macos-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: npm install
      run: npm install
    - name: build application
      run: npm run build
    - name: create release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        draft: true
        files: |
          dist/*.dmg
          dist/*.dmg.blockmap
          dist/*.zip
          dist/latest-mac.yml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_on_win:
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: npm install
      run: npm install
    - name: build application
      run: npm run build
    - name: create release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        draft: true
        files: |
          dist/*.exe
          dist/*.exe.blockmap
          dist/latest.yml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
